name: Scheduled Job Scrape

on:
  # This schedule runs the script automatically every 3 days.
  # The syntax is a CRON expression.
  schedule:
    - cron: '0 0 */3 * *'
  
  # This line allows you to run the workflow manually from the GitHub Actions tab for testing.
  workflow_dispatch:

jobs:
  scrape:
    # Use the latest version of Ubuntu as the runner.
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository code.
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up the specific version of Python you are using.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install all the Python libraries listed in your requirements.txt file.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run your main Python script.
      - name: Run the job scraper
        # This 'env' block securely passes your GitHub Secrets to the script as environment variables.
        env:
          JIRA_SERVER: ${{ secrets.JIRA_SERVER }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_REQUEST_PROJECT_KEY: ${{ secrets.JIRA_REQUEST_PROJECT_KEY }}
          JIRA_OUTPUT_PROJECT_KEY: ${{ secrets.JIRA_OUTPUT_PROJECT_KEY }}
          JIRA_FIELD_COMPANY_NAME: ${{ secrets.JIRA_FIELD_COMPANY_NAME }}
          JIRA_FIELD_CAREERS_URL: ${{ secrets.JIRA_FIELD_CAREERS_URL }}
          JIRA_FIELD_KEYWORDS: ${{ secrets.JIRA_FIELD_KEYWORDS }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py
