name: Python Job Scraper

on:
  workflow_dispatch: # Allows you to run it manually
  schedule:
    - cron: '0 0 * * *' # Runs once a day at midnight

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Or your desired version

    # --- ADD THIS CACHING STEP ---
    - name: Cache pip and WebDriver
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.wdm
        key: ${{ runner.os }}-pip-webdriver-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-webdriver-

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Scraper
      env:
        # Add all your secrets here
        JIRA_SERVER: ${{ secrets.JIRA_SERVER }}
        JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_REQUEST_PROJECT_KEY: ${{ secrets.JIRA_REQUEST_PROJECT_KEY }}
        JIRA_OUTPUT_PROJECT_KEY: ${{ secrets.JIRA_OUTPUT_PROJECT_KEY }}
        JIRA_FIELD_COMPANY_NAME: ${{ secrets.JIRA_FIELD_COMPANY_NAME }}
        JIRA_FIELD_CAREERS_URL: ${{ secrets.JIRA_FIELD_CAREERS_URL }}
        JIRA_FIELD_KEYWORDS: ${{ secrets.JIRA_FIELD_KEYWORDS }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python main.py
